### ISSUE TITLE
Blocked on "Loading movie info"

### ISSUE THREAD

**Issue by AltarBeastiful** [RuudBurger/CouchPotatoExtension#6]
When I activate the extension, the panel gets stuck on "Loading movie info".
Tested with chromium 39 and firefox 34 on IMDB. 

With chromium I get this exception in the console : 
```
Error in event handler for (unknown): TypeError: Cannot read property 'length' of undefined
    at Object.queryApi.onComplete (eval at <anonymous> (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:1:169), <anonymous>:1504:44)
    at eval (eval at <anonymous> (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:1:169), <anonymous>:1683:14)
    at chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:3:3
    at Object.d.onSuccess (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:19:13)
    at Object.n [as KangoInvokeAsyncModule_result] (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:17:425)
    at Array.<anonymous> (chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:18:226)
    at chrome-extension://jochingjncojldfclaicaomboafaiong/includes/content.js:13:292
```

How can I build the extension without minifying? I'd like to find this one ;)

**Comment by RuudBurger** [comment]
Are you still having this issue?
